### ISSUE TITLE
Debug logging or callback

### ISSUE THREAD

**Issue by djmitche** [tlewowski/zurvan#46]
It would be great to log each moment in time during an `advanceTime` call, for help debugging.

This could be done using the `debug` package, or just by allowing the user to provide a callback called each time the clock advances to the next timer.

**Comment by tlewowski** [comment]
@djmitche thanks for using zurvan! 

I agree that logging would be useful.

I'm doing my best to keep `zurvan` dependency-less, so it'd probably be some configuration parameter.

I'll take care of it once I have some free time, probably next week. If you want it faster, feel free to fork & issue a pull request, I'll be happy to accept one.

**Comment by djmitche** [comment]
My "hack" to make this happen was to add it to `TimeUnit.setTo`, but that class doesn't seem to get any configuration.  Is there a place this might fit better?

**Comment by tlewowski** [comment]
I'd recommend the following locations for logging:

 - `zurvan.js` - `interceptTimers` (start of processing), `releaseTimers` and `forcedReleaseTimers` (end of processing)
 - `detail/TimeForwarder.js` - `advanceTime` (actual time "movement") and `blockSystem` (simulation of blocking calls)
 - `detail/TimerInterceptor.js` and `detail/ImmediateInterceptor.js` - if you want to trace every call to `setTimeout`/`setInterval`/`setImmediate` (and possibly dump a stack or something)
 - `detail/TimerRepository.js` may also be considered if you want to trace things like "number of awaiting timeouts" etc.
