### ISSUE TITLE
Please lint :)

### ISSUE THREAD

**Issue by djmitche** [tlewowski/zurvan#49]
Many files in Zurvan have a mix of tabs and spaces, even on the same line.  The result is that, unless I have the same tab settings, the code looks like it was indented in a freak cat-on-keyboard incident.

It would be great to pick one or the other (preferably spaces) and enforce it using eslint.

**Comment by djmitche** [comment]
(I would do this but of course it will conflict with any other work in progress or pull requests, so it's best done by a maintainer)

**Comment by tlewowski** [comment]
done in 8ce825c75331f1f97321ae7cd7fd06babdd9f8dc

**Comment by djmitche** [comment]
Wow, thanks :D
